### ISSUE TITLE
[Feature request] Custom citation formats (parse modes)

### ISSUE THREAD

**Issue by bb010g** [Langenscheiss/bibitnow#12]
I have a personal style for sending links over instant messaging, and it'd be nice if bibitnow could generate straight from its metadata to that instead of having to go through intermediary external parsing & transformation.

Looking at the source, this is handled in `/popup/parser/popup_parse_*.js` files, and their structure doesn't look too great for dropping in a user-provided script, so if this isn't currently feasible or would take time to get to (this is a low priority request), it's understandable.

(If a patch implementing this (or any other feature/bugfix) was written, how would you prefer to receive it, and would you likely take it? Having the full source code on some sort of forge would be nice, even if it's just stuck up there with a disclaimer that the structure & style may be weird and you don't plan to spend time dealing with proposed changes to non–site-adjuster parts of the extension.)

**Comment by Langenscheiss** [comment]
Hi.

My long term goal with the markup language available for the redirection links is to have custom style support. However, currently, the markup is not flexible enough for that (with regexp support being one milestone towards what is necessary). Unfortunately, my job takes away so much time right now. I can barely maintain the plugin. However, there is indeed custom citation styles planned. The intention is to have something a bit more quick and dirty than citation style files, and, in the end, import and export between citation style files (.csl) and the bibitnow markup. 

Sorry that I cannot make any prediction right now when this arrives, but I am having it on my list.

/Langenscheiss

**Comment by Langenscheiss** [comment]
Hi.

I am glad to announce that the next version will have support for custom citation formats. It's based on the internal formatArray system, which is nothing but a json object. You will find a reference for how to write such a formatArray in JSON on the option page. The good news is that it supports flow control, meaning you can display certain bibfields depending on whether other bibfields are available (= they yield a non-empty string). Combined with regular expression replacements and backreferences, this should be pretty flexible, i. e., you can for example ask whether the bibfield "type" is a certain type ("article","book", etc.) and, depending on the outcome, proceed by parsing other bibfields. The bad news is that the system has not the most intuitive syntax, as it was originally intended as an internal format only, and advanced flow control requires regular expressions (if you are interested in whether the bibfield contains any string). However, I realized that in order to support recursive flow control, this was the easiest, least time consuming choice for now. I hope that I will be able to support CSL files eventually. 
Moreover, I plan to support custom parser specific options at some point. Those will essentially be flags that one can query using the same formatArray system.

**Comment by Langenscheiss** [comment]
Custom formats should be supported now. CSL support will take a while though. No time right now. Hope you manage to build your desired output format. It's flexible, but a bit cumbersome.

**Comment by Langenscheiss** [comment]
You can contribute your own style now. See in citationStyles

**Comment by bb010g** [comment]
Thank you so much! :heart:
