### ISSUE TITLE
Use "urldate" instead of "note" for access date

### ISSUE THREAD

**Issue by rugk** [Langenscheiss/bibitnow#16]
Lualatex/biber do support "urldate". That is way nicer than the comment, which cannot be translated and is just inserted as a "note".

cf.: https://tex.stackexchange.com/questions/48983/urldate-in-bibtex-gets-ignored

**Comment by Langenscheiss** [comment]
Hi.

Thanks for the various suggestions. :)

In general, I need to stress that I am not a big fan of any "x" instead of "y" solution. My philosphy is to support as much as possible/I am aware of. Hence, this issue will be solved in the next version by making both the note and the urldate optional fields just as the iso date, with the default set to what it is right now. Any biber/lualatex user can then simply configure the program to what they like most.

**Comment by Langenscheiss** [comment]
The urldate field should now be accessible. The notes can be turned off using the "Additional notes" option

**Comment by rugk** [comment]
Fixed, I guess. Thanks. :smiley:
