### ISSUE TITLE
Bug: journal capitalization in PubMed

### ISSUE THREAD

**Issue by lotard** [Langenscheiss/bibitnow#21]
When adding citation from PubMed (but NOT publisher's site), with "Abbreviate journal" option unchecked, journal names are capitalized using "Sentence case", rather than the more appropriate "Capitalize Every Word Case".

Publisher's website (https://genome.cshlp.org/content/30/4/528), "Abbreviate journal" option unchecked (correct case):
![image](https://user-images.githubusercontent.com/7230877/81432473-d611fd80-9117-11ea-9c30-9383027bd1c5.png)
Pubmed, "Abbreviate journal" option checked (correct case):
![image](https://user-images.githubusercontent.com/7230877/81432443-c692b480-9117-11ea-9710-68f22d45c855.png)
Pubmed, "Abbreviate journal" option unchecked (incorrect case):
![image](https://user-images.githubusercontent.com/7230877/81432408-b8449880-9117-11ea-975b-46d86e4267eb.png)

**Comment by Langenscheiss** [comment]
Hi.
Thanks for letting me know. This is down to the site adjuster for Pubmed. Apparently I should fetch the journal name from a better place in the website source. Gonna look into this.
In general, I have to say that Pubmed is hands down the most annyoing website my plugin supports when it comes to how it provides meta data. Why can't they just do it like any serious publisher and put standard meta tags.

**Comment by lotard** [comment]
I would probably just capitalize the name itself (except non-initial "of", "a", "the", "with" etc, like in movie titles)

**Comment by Langenscheiss** [comment]
The general assumption is that the publisher knows best how to write the journal name. This clearly does not work for pubmed, so it's either a better source for the journal name, or a capitalization as you suggest. Already the statically retrieved author names undergo extensive formatting on this website due to their shitty formatting. Gosh, I hate pubmed, but it's important so I support it. It should be fixed in the next version.

**Comment by Langenscheiss** [comment]
It should be fixed in 0.884/0.885 (the latter including just a minor adjustment of the icon for the Chrome webstore)
