### ISSUE TITLE
Bug: default month?

### ISSUE THREAD

**Issue by lotard** [Langenscheiss/bibitnow#22]
It seems like when month doesn't get parsed it defaults to Jan (https://genome.cshlp.org/content/30/4/528):
![image](https://user-images.githubusercontent.com/7230877/81432999-b8916380-9118-11ea-999c-fefe8d509daa.png)
It is correctly parsed in PubMed (Apr) btw.

Parsing will fail sometimes, but is it possible for it to default to some other value (XXX?), so it's easy to spot and manually correct?

**Comment by Langenscheiss** [comment]
Hi.
Thanks for letting me know.
This has nothing to do with default behavior. It's just the website using the annoying MM-DD-YY date format instead of the systematic YY-MM-DD or DD-MM-YY formats. I have tried to implement ways of telling the extension to recognize this format, but in case of 1st of April, it is ambiguous, so if the website does not signal that it's using this format, it's down to manual tuning at the moment. Really annoying!

**Comment by lotard** [comment]
Ah, don't know what's the standard way of dealing with it other than maintaining a list of websites, but maybe one can tell if it's American or not in some other way? Not a huge problem though.

**Comment by Langenscheiss** [comment]
Fixed in next version. I am simply going to set a site adjuster for this publisher. Should not take too long.

**Comment by Langenscheiss** [comment]
Should be working properly in 0.844
