### ISSUE TITLE
Funky behaviour with JSTOR DOIs

### ISSUE THREAD

**Issue by episanty** [Langenscheiss/bibitnow#24]
This is probably a bug in JSTOR rather than BibItNow, but it feels like it should still receive some handling from BibItNow.

JSTOR sometimes lists papers that don't have DOIs, but it seems it's not always clear whether this is the case or not. My particular stumbling-example today is https://www.jstor.org/stable/24953986, which explicitly lists the DOI 10.2307/24953986 multiple times in the html source; however, going to https://doi.org/10.2307/24953986 returns an unresolved DOI.

Ultimately, this seems to be buggy behaviour by JSTOR - they should either correctly resolve the DOI, or stop reporting it in their html metadata. I've contacted JSTOR and they seem to understand the problem and have logged it with their dev and metadata teams, but even if they fix the issue (by removing the DOI claims or by hashing it out with CrossRef) that'll take some time. For the moment it seems that no DOI beginning with 10.2307 will resolve at CrossRef.

In the meantime, however, BibItNow is currently reporting that value as the DOI field in the bibtex output, which feels wrong to me -- until they resolve correctly, they should be dropped from the output shown to the user (or, even better, they should be replaced with some indicator that it's a JSTOR stable ID).

**Comment by Langenscheiss** [comment]
I noticed that too. JSTOR really has a really strange idea about the purpose of DOIs. For years btw. So don't expect them to do anything about it. Unfortunately, I don't have any automatic way of checking whether the doi resolves unless I ask for permission to cross-link to the doi system. However, I am very careful in asking extra permissions from the user. And recently, the google chrome team is beginning to ask why a certain permission is asked for by the extension. Now, this one is probably a safe one and easy to argue, but for the moment, it's easier to simply drop all the 10.2307 DOIs. That can be done with a one-liner in the jstor adjuster. I need to update the JSTOR adjuster anyhow. 
So that should be fixed in the next version. Thanks for reporting :)

**Comment by Langenscheiss** [comment]
Fixed in  version 0.887
