### ISSUE TITLE
Question: how to lowercase the bibkey generated string?

### ISSUE THREAD

**Issue by eugenio** [Langenscheiss/bibitnow#38]
I couldn't find a way to format the bibkey item of an entry in order to make it all lowercase including the initial of the author:

`{!authors[0,0]}}_{year||access_year}`

outputs : 

`Author_year` i.e.  `Dough_1960`

while I wanted :

`author_year`   i.e.  `dough_1960`

I searched the instruction for a hint but i could't find any.
I apologize if it's there and i didn't find it.

**Comment by Langenscheiss** [comment]
Hi.
That's a good question. Unfortunately, it's not supported yet because javascript regexps don't know the \L statement. This would allow you to put everything to lower case/upper case, see here

https://stackoverflow.com/questions/20742076/regex-replace-uppercase-with-lowercase-letters

 However, I think I can bring those statements back by essentially refining the string replace routine implemented into bibitnow. I will try to make it work for the next build. Then, you will be able to put characters into lower case using regexps and the \L command (and the upper case equivalent of course). Your solution would then be

`{!authors[0,0]\\\/(\w)/\L{$1}/g/}{year}

**Comment by eugenio** [comment]
Thanks,
I think that this issue can be closed since I found how to make the Jabref extension work.
I was using BibIt as an alternative way to import reference into Jabref.
Sorry for the noise.

**Comment by Langenscheiss** [comment]
Ok.
I have added support anyhow. Just didn't have much time recently to update, due to work taking priority.

**Comment by Langenscheiss** [comment]
Just in case anyone else is interested, here is the example from the option page

{authors[0,0]\\\/(.{3})/\U{$1}//}

This code converts the first 3 letters of the group defined in the regular expression to upper case. Lower case conversion is achieved with \L{} instead :)
