### ISSUE TITLE
[QUESTION] Article abbreviation in format surnameYYYYword

### ISSUE THREAD

**Issue by mgarort** [Langenscheiss/bibitnow#43]
First of all, thank you so much for this plugin! I was looking for something that would allow me to get the bibtex as efficiently as possible, and bibitnow is perfect for my workflow.

Now to the question: I am wondering if it is possible to obtain the article abbreviation (i.e. the reference that gets cited in the Latex text body as `\cite{abbreviation}`) in the format `surnameYYYYword`, instead of the default `SurnameYYYYMonth`. `surnameYYYYword` is the format used by Google Scholar, and I find it more intuitive and easier to track.

 I have checked the issue list and I haven't found this asked before, but sorry if the info is already there and I have missed it.

**Comment by Langenscheiss** [comment]
Hi
Yes, it is possible using the bibkey customization in global options and regular expressions. At least more or less. Try this format string. 

{!authors[0,0]\\\/(.{1})/\L{$1}//}{year||access_year}{title\\\/[\s].*$///(.{1})/\L{$1}//}

The first regular expression separates the title after the first space character, so in most cases you should get the first word. The second regular expression converts the first character from upper case to lower case. 

I will have to commit a small update to BibItNow soon because it needs to comply with the latest ChromeStore restrictions. I will add this as an example to the instructions in the options!

Sorry for the lack of updates. I am almost done with my paper, so soon^(tm) I will have some time to update bibitnow more extensively.

**Comment by mgarort** [comment]
This is amazing! Thank you so much! :D

I am using it in Firefox so I haven't noticed any problem.

Good luck with your paper!
