### ISSUE TITLE
Recognize web site metadata

### ISSUE THREAD

**Issue by hildogjr** [Langenscheiss/bibitnow#44]
I use [Zotero](https://www.zotero.org/download/) for long time and it regonize the page meta data not just the title. For example, the pages:

- https://ieeexplore.ieee.org/document/7910332 is not recognized, Zotero Firefox Browser plugin recognize all the bellow information:

![image](https://user-images.githubusercontent.com/2211474/113766513-e483e300-96f3-11eb-80e1-dbfb988abd22.png)

- https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7910332 (PDF file of the above link) give the same result on Zotero and the bellow on "Bib it now!"
```
@misc{BibEntry2021Apr,
	title = {{IEEE Xplore Full-Text PDF:}},
	year = {2021},
	month = {Apr},
	note = {[Online; accessed 6. Apr. 2021]},
	url = {https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7910332}
}
``` 

This show that the plugin doesn't recognize the meta data on the page. Zotero have the only down side that I have to import the reference and after export to file, "Bib it now!" should make this procedure straightforward. The expected result for the above pages should be:

```
@inproceedings{taher_model_2017,
	title = {Model predictive control of {PV}-based shunt active power filter in single phase low voltage grid using conservative power theory},
	doi = {10.1109/PEDSTC.2017.7910332},
	abstract = {Among different renewable energy sources, photovoltaic ({PV}) energy conversion systems connected to the grid via an interfacing converter have grown very fast. The system power quality is affected by nonlinear loads. This paper presents a control scheme for power electronics converters to mitigate current harmonics and control of the injected active power into the electrical grid which is generated by {PV} system. These objectives are achieved by using the conservative power theory ({CPT}). Finite control set model predictive control ({FS}-{MPC}), is used as proposed switching algorithm. Finally, simulation results using {MATLAB}-Simulink demonstrate the effectiveness and performance of the {FS}-{MPC} switching algorithm in comparison with hysteresis switching algorithm.},
	eventtitle = {2017 8th Power Electronics, Drive Systems Technologies Conference ({PEDSTC})},
	pages = {253--258},
	booktitle = {2017 8th Power Electronics, Drive Systems Technologies Conference ({PEDSTC})},
	author = {Taher, S. A. and Alaee, M. H. and Arani, Z. Dehghani},
	date = {2017-02},
	keywords = {Active filters, conservative power theory, Harmonic analysis, hysteresis, Hysteresis, model predictive control, Power filters, Power harmonic filters, power quality, {PV}-based shunt active power filter, shunt active power filter, Switches},
}
```

**Comment by Langenscheiss** [comment]
Hi.
Thanks for letting me know. I was recently busy with science projects so I could not update the site adjusters as regularly. Zotero constantly works because they have an army of people constantly updating their site specific code. I don't have that, so unfortunately, these things happen. I will try to get ieeexplore working again in the next version.

**Comment by hildogjr** [comment]
Yes, development of free software this dependence (people/programmers help)...

I was think to borrow (if the license is compatible) this part of recognize from the Zotero (https://github.com/zotero/zotero-connectors - AGPLv3 license). It have the advantage, as far I test, of recognize even the book collection page of the universities or import multiple references at once (for example, from https://www.google.com/search?tbm=bks&q=electrical+circuits).

Maybe, we could update in the sense of prioritize the metadata and use the current recognize of BibitNow if metadata not present. Which will allow the importation of PDF that haven't such information.

**Comment by Langenscheiss** [comment]
It's not that easy. One of the principles of bibitnow is to not ask any but the absolutely necessary permissions from the user. The other is to not use any code that I don't understand myself. So simply relying on Zotero code is not an option, and importing multiple references from different sources is not permitted when not asking for global host permissions -- something Zotero does but I would never do because of security reasons (I am not a security expert, so I try to avoid security issues by asking as few permissions from the user as necessary)
Moreover, its not just about borrowing that code. It's about updating it. So basically every time there is an update to the site specific code of Zotero, I would have to check that into BibItNow. So no, I am not going to do that. 
Regarding ieee, I am confident I can fix the issues. I have not been updating the site adjuster for that website in a long time. I working on it right now. Regarding other websites, people can always make a request here in the forums to have a look at it. Or even better, write your own adjuster and submit it to me with proper credits given of course.

**Comment by Langenscheiss** [comment]
Hi.
The latest version 0.902 should work better on IEEExplore. The document above produces an "incollection" bibitex item. It does not support the event key yet, so it puts it into journal. It's not perfect, but should suffice in most cases.

**Comment by hildogjr** [comment]
Yes. It worked in all testes until now, you can close the this thread.
