### ISSUE TITLE
Page number with letter

### ISSUE THREAD

**Issue by ingstra** [Langenscheiss/bibitnow#50]
I got this error when checking references while trying to submit to an APS paper:

`WARNING: Rapid Comm. not cited properly; use page number 030102(R)`

The paper in question is [this one](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.87.030102), though I also got the same error for another paper. It seems the bibitnow `pages` leaves out the (R) and only gives the number.

**Comment by Langenscheiss** [comment]
Hi.
Oh thanks. Thats an issue of preferring the dynamically loaded citation over static information. I will change that for the next point release (probably tomorrow). For now, you can disable dynamic citation in the global options. For most common physics journals, the static meta data is acceptable.

**Comment by Langenscheiss** [comment]
There is also another issue with this. When submitting to APS, they always want the (R) extension. However, when citing a rapid comm in a paper for another, non-aps journal, ADDING the (R) extension in fact results in an error. So perhaps I can fix this by adding a bibtex option allowing to remove letter characters from the pages field. But that's kind of wacky as well, because some pages in some journals are in fact states as letters. Perhaps something in between. No idea tbh.

**Comment by ingstra** [comment]
Åhå.. Ah well, you can maybe leave it as is then. It's not so cumbersome to add the (R) manually.
